version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/go/src/app  # Монтируем текущую директорию в контейнер для разработки

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/agent"]
    volumes:
      - .:/go/src/app

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/orchestrator"]
    volumes:
      - .:/go/src/app
